// examples/react/src/App.tsx
import { useRef } from "react";
import "./App.css";
import { useRegisterSW } from "rsbuild-plugin-pwa_vm/react";

const App = () => {
  const offlineReadyDialogRef = useRef<HTMLDialogElement>(null);
  const {
    skipWaiting,
    newSwWaiting: [newSwWaiting],
    newSwActive: [newSwActive],
  } = useRegisterSW({
    onOfflineReady() {
      offlineReadyDialogRef.current?.showModal();
    },
  });
  return (
    <>
      <div className="content">
        <h1>Rsbuild with React</h1>
        <p>Start building amazing things with Rsbuild</p>
        <p>(and rsbuild-plugin-pwa)</p>
        {newSwWaiting && (
          <div>
            <p>New version is available</p>
            <button
              type="button"
              onClick={function acceptUpdate() {
                skipWaiting();
              }}
            >
              Install
            </button>
          </div>
        )}
        {newSwActive && (
          <div>
            <p>
              Update is installed. Refresh the page or something bad is gonna
              happen
            </p>
            <button
              onClick={function confirmPageRefresh() {
                window.location.reload();
              }}
              type="button"
            >
              If you say so
            </button>
          </div>
        )}
      </div>
      <dialog
        ref={offlineReadyDialogRef}
        onCancel={function () {
          offlineReadyDialogRef.current?.close();
        }}
      >
        <p>The app is ready to work offline</p>
        <button
          type="button"
          onClick={function () {
            offlineReadyDialogRef.current?.close();
          }}
        >
          Cool
        </button>
      </dialog>
    </>
  );
};

export default App;

// examples/solid/src/App.tsx
import { Show } from "solid-js";
import "./App.css";
import { useRegisterSW } from "rsbuild-plugin-pwa_vm/solid";

const App = () => {
  let offlineReadyDialogRef: HTMLDialogElement | undefined;

  const {
    skipWaiting,
    newSwWaiting: [newSwWaiting, setNewSwWaiting],
    newSwActive: [newSwActive],
  } = useRegisterSW({
    onOfflineReady() {
      offlineReadyDialogRef?.showModal();
    },
  });

  return (
    <>
      <div class="content">
        <h1>Rsbuild with SolidJS</h1>
        <p>Start building amazing things with Rsbuild</p>
        <p>(and rsbuild-plugin-pwa)</p>

        <Show when={newSwWaiting()}>
          <div>
            <p>New version is available</p>
            <button type="button" onClick={() => skipWaiting()}>
              Install
            </button>
            <button type="button" onClick={() => setNewSwWaiting(false)}>
              Dismiss
            </button>
          </div>
        </Show>

        <Show when={newSwActive()}>
          <div>
            <p>
              Update is installed. Refresh the page or something bad is gonna
              happen
            </p>
            <button type="button" onClick={() => window.location.reload()}>
              If you say so
            </button>
          </div>
        </Show>
      </div>

      <dialog
        ref={offlineReadyDialogRef}
        onCancel={() => offlineReadyDialogRef?.close()}
      >
        <p>The app is ready to work offline</p>
        <button type="button" onClick={() => offlineReadyDialogRef?.close()}>
          Cool
        </button>
      </dialog>
    </>
  );
};

export default App;
